commands = ["rate",
            "stats",
            "stat",
            "setting",
            "language",
            "pick",
            "suggest",
            "values",
            "desc",
            "difficulty",
            "frequency"]
